/*
 * @Author: hrd
 * @Date: 2022-04-28 18:24:23
 * @Description: 控制器 模块 id
 */
/** 控制器id */
/** 与功能表关联，ID顺序不可以改变，新增往后加1 */
export enum ControllerIds {
    /** 默认值 无模块id */
    Normall = -1,
    /** 登录 */
    LoginController = 2,
    /** 大厅 */
    LobbyController = 3,
    /** 主角 */
    RoleController = 4,
    /** 背包 */
    BagController = 5,
    /** GM */
    GMController = 6,
    /** 兑换 */
    ExchangeController = 7,
    /** 充值 */
    RechargeController = 8,
    /** 邮件 */
    MailController = 9,
    /** 熔炼 */
    SmeltController = 10,
    /** 强化 */
    StrengthController = 11,
    /** 首领 */
    BossController = 12,
    /** 聊天 */
    ChatController = 13,
    /** 战斗结算 */
    BattleResultController = 14,
    /** 常规游戏服务端数据 */
    GameController = 15,
    /** 称号 */
    TitleController = 16,
    /** 打造 */
    BuildController = 17,
    /** 进阶 */
    GradeController = 18,
    /** 升星 */
    UpStarController = 19,
    /** 西域行商 */
    SilkRoadController = 100,
    /** 游历天下 */
    AdventureController = 101,
    /** 属性 */
    AttrFvController = 20,
    /** 角色时装 */
    RoleSkinController = 21,
    /** 角色技能 */
    RoleSkillController = 22,
    /** 竞技场 */
    ArenaController = 23,
    /** 官职 */
    RoleOfficialController = 24,
    /** 官职-军衔 */
    ArmyLevelController = 25,
    /** 材料副本 */
    MaterialController = 26,
    /** 武将系统 */
    GeneralController = 27,
    /** 出战单位 */
    BattleUnitController = 28,
    /** Vip */
    VipController = 29,
    /** 商城 */
    ShopController = 30,
    /** 名将来袭（世界BOSS） */
    WorldBossController = 31,
    /** 关卡界面Win */
    GameLevelController = 32,
    /** * 关卡通行证 */
    GamePassController = 33,
    /** 挂机 */
    OnHookController = 34,
    /** 签到 */
    DaySignController = 35,
    /** 展示物品的跳转 */
    ItemTipsController = 36,
    /** 常驻排行榜 */
    RankListController = 37,
    /** 展示物品跳转（其他附带属性的物品） */
    ItemTipsExController = 38,
    /** 活动模板 */
    ActivityController = 39,
    /** 虎符官印 */
    SealAmuletController = 40,
    /** 系统设置 */
    SettingController = 41,
    /** 红颜 */
    BeautyController = 42,
    /** 烽火连城 */
    BeaconWarController = 43,
    /** 武将招募 */
    GeneralRecruitController = 44,
    /** 组队 */
    TeamController = 45,
    /** 头像头像框 */
    HeadController = 46,
    /** 好友 */
    FriendController = 47,
    /** 世家 */
    FamilyController = 48,
    /** 博物志 */
    CollectionBookController = 49,
    /** 布阵 */
    PlanController = 50,
    /** 华服 */
    RoleSpecialSuitController = 51,
    /** 炼体 */
    RoleExerciseController = 70,
    /** 押镖 */
    EscortController = 52,
    /** 排位赛 */
    RankMatchController = 53,
    /** 日常周常任务 资源找回 */
    DailyTaskController = 54,
    /** 华容道 */
    HuarongdaoController = 55,
    /** 军师 */
    AdviserController = 56,
    /** 功能预告 */
    FuncPreviewController = 56,
}
