/*
 * @Author: kexd
 * @Date: 2022-07-27 17:00:06
 * @Description: 功能id枚举
 */

/** 功能id（注意按大小放置哗） */
export enum FuncId {
    /** 关闭所有界面 */
    CloseAll = 1,
    /** 飘字提示 */
    MsgToast = 2,
    /** 弹窗提示 */
    MsgBox = 3,

    /** 角色 */
    Role = 6,
    /** 关卡 */
    GuanKa = 7,
    /** 关卡同行证 */
    GuankaPass = 8,
    /** 挂机 */
    OnHook = 9,

    /** 背包 */
    Bag = 16,
    /** 邮件 */
    Mail = 17,
    /** 合成 */
    Material = 18,
    /** 快速挂机 */
    OnHookQuick = 20,
    /** 官职 */
    RoleArmyOfficial = 32,
    /** 官职军衔 */
    RoleArmyLevel = 33,
    /** 熔炼 */
    Smelt = 34,

    /** 官职官印 */
    OfficialSeal = 35,
    /** 官职虎符 */
    OfficialAmulet = 36,
    /** 排行榜-本服 */
    RankListLocal = 37,
    /** 排行榜-跨服 */
    RankListCross = 38,
    /** 好友 */
    Friend = 39,
    /** 头像 */
    Head = 40,
    /** 头像框 */
    HeadFrame = 41,
    /** 红装熔炼 */
    RedSmelt = 42,
    /** 进阶熔炼 */
    GradeSmelt = 43,
    /* 气泡 */
    ChatBubble = 44,
    /** 功能预告 */
    FuncPreview = 45,
    /** 更多入口 */
    MoreEntrance = 46,
    /** 国士 */
    BeautyEntrance = 47,
    /** 首领入口 */
    BossEntrance = 48,
    /** 角色入口 */
    RoleEntrance = 49,
    /** vip */
    Vip = 50,
    /** 进阶入口 */
    GradeEntrance = 51,
    /** 副本入口 */
    FBEntrance = 52,
    /** 排行榜-入口 */
    RankListEntrance = 53,
    /** 坐骑 */
    Horse = 101,
    /** 羽翼 */
    Wing = 111,
    /** 光武 */
    Weapon = 121,
    /** 红颜才艺进阶 */
    BeautyGrade = 131,
    /** 军师智略 */
    AdviserGrade = 141,
    /** 萌宠 */
    Pet = 151,

    /** 称号 */
    Title = 201,

    /** 时装 */
    Skin = 301,
    /** 时装注灵 */
    SkinZhuling = 302,
    /** 时装炼神 */
    SkinLianshen = 303,
    /** 时装套装 */
    SkinSuit = 304,
    /** 活动套装/荣誉套装 */
    SkinHuodongSuit = 305,
    /** 异域套装 */
    SkinYiyuSuit = 306,
    /** 仙装 */
    SkinSpecialSuit = 311,
    /** 炼体丹药 */
    RoleExercise = 56,

    /** 布阵 */
    PlanPage = 1001,
    /** 组队阵容 */
    TeamPlanPage = 1002,

    /** 装备-入口 */
    EquipEntrance = 2000,
    /** 装备-强化 */
    EquipStrength = 2001,
    /** 装备-升星 */
    EquipUpStar = 2002,
    /** 装备-打造 */
    EquipBuild = 2003,
    /** 西域行商 */
    SilkRoad = 6002,
    /** 游历天下 */
    Adventure = 6003,

    /** 装备-宝石 */
    EquipGem = 2004,
    /** 本服首领 */
    BossLocal = 2100,
    /** 个人boss */
    BossPersonal = 2101,
    /** 至尊boss */
    BossVip = 2102,

    /** 竞技场入口 */
    ArenaEntrance = 2200,
    /** 竞技场 */
    Arena = 2201,
    /** 排位赛 */
    RankMatch = 2202,

    /** 主角-技能（一级页签） */
    RoleSkillOnetab = 2300,
    /** 主角-技能 */
    RoleSkill = 2301,
    /** 主角-绝学 */
    RoleUniqueSkill = 2302,
    /** 主角-武艺 */
    RoleMaritialSkill = 2303,

    /** 材料副本 */
    MaterialFB = 2401,
    /** 名将来袭（世界boss） */
    WorldBoss = 2501,
    /** 烽火连城 */
    BeaconWar = 2601,
    /** 通用boss */
    MulitBoss = 2701,
    /** 组队副本 */
    Team = 2801,

    /** 武将入口 */
    GeneralEntrance = 3000,
    /** 武将 */
    General = 3001,
    /** 武将-皮肤 */
    GeneralSkin = 3002,
    /** 武将-战马 */
    GeneralHorse = 3003,
    /** 武将-神兵 */
    GeneralWeapon = 3004,
    /** 武将-升品 */
    GeneralQualityUp = 3005,
    /** 武将-重生 */
    GeneralReborn = 3006,
    /** 武将-图鉴 */
    GeneralBook = 3007,
    /** 武将-升级 */
    GeneralLevelUp = 3008,
    /** 武将-升阶 */
    GeneralGradeUp = 3009,
    /** 武将-觉醒 */
    GeneralAwaken = 3010,
    /** 武将-突破 */
    GeneralBreak = 3011,
    /** 武将-战技 */
    GeneralSkill = 3012,
    /** 武将-装备 */
    GeneralEquip = 3013,
    /** 武将-合成 */
    GeneralCompose = 3014,

    /** 红颜 */
    Beauty = 3101,
    /** 红颜-升级 */
    BeautyUpLevel = 3102,
    /** 红颜-升星 */
    BeautyUpStar = 3103,
    /** 三国探险 */
    FBExplorePage = 3201,
    /** 军师升级 */
    Adviser = 3301,
    /** 军师进阶 */
    AdviserUpGrade = 3302,
    /** 军师专精 */
    AdviserMastery = 3303,
    /** 博物志/博物志-见闻 */
    CollectionBook = 4101,
    /** 博物志-生涯 */
    CollectionBookCareer = 4102,
    /** 博物志-人物 */
    CollectionBookPerson = 4103,
    /** 博物志-奇物 */
    CollectionBookWonder = 4104,

    /** 世家 */
    FamilyHome = 5001,
    /** 世家-世家 */
    FamilyFamily = 5002,
    /** 世家-成员 */
    FamilyMember = 5003,
    /** 世家-事务 */
    FamilyTask = 5004,
    /** 族长争夺 */
    FamilyPatriarch = 5005,
    /** 族长争夺-伤害排行 */
    FamilyPatriarchRank = 5006,
    /** 世家-校场 */
    FamilyDrillGround = 5007,
    /** 世家-图腾 */
    FamilyTotem = 5008,
    /** 世家-试炼副本 */
    FamilyTrialCopy = 5009,

    /** 主界面日常 */
    Daily = 6000,
    /** 日常-押镖 */
    Escort = 6001,
    /** 日常-华容道 */
    Huarongdao = 6004,

    /** 日常任务 */
    DailyTask = 7001,
    /** 周常任务 */
    WeeklyTask = 7002,
    /** 资源找回 */
    ResRecovery = 7003,
    /** 世界等级 */
    WorldLevel = 8001,

    /** 道具商城 */
    ItemShop = 12001,
    /** VIP商城 */
    VipShop = 12002,
    /** 伙伴商城 */
    PartnerShop = 12003,
    /** 仙踪商城 */
    XianzongShop = 12004,
    /** 竞技商城 */
    ArenaShop = 12005,
    /** 声望商城 */
    ShenWangShop = 12006,
    /** 灵兽商城 */
    AnimalShop = 12007,
    /** 战技商城 */
    GeneralShop = 12008,
    /** 折扣商城 */
    DiscountShop = 12009,
    /** 世家商城 */
    FamilyShop = 12010,
    /** Boss商城 */
    BossShop = 12011,
    /** 神秘商城 */
    SecretShop = 12012,
    /** 华容道商店 */
    HuarongdaoShop = 12013,
    /** 武将商城 */
    WuJiangShop = 12016,

    // ----------注意按id大小放在对应位置-----------------

}
