/*
 * @Author: hrd
 * @Date: 2022-03-31 18:34:02
 * @Description:
 */
export enum UI_PATH_ENUM {
    WinBig = 'prefab/com/win/WinBig',
    WinTab = 'prefab/com/win/WinTab',
    WinTabBtn = 'prefab/com/win/WinTabBtn',
    /** 非大窗口，标题样式1 */
    WinSmall = 'prefab/com/win/WinSmall',

    /** GM窗口 */
    GMWin = 'prefab/gm/GMWin',
    /** GM快捷页 */
    GMQuickPage = 'prefab/gm/GMQuickPage',
    /** GM命令页 */
    GMCommandPage = 'prefab/gm/GMCommandPage',
    /** 消息提示 */
    MsgToast = 'prefab/msgtoast/MsgToast',
    /** 角色 */
    player = 'prefab/player/player',
    /** 角色昵称 */
    ActorNickBox = 'prefab/player/ActorNickBox',
    /** 挑战及复活 */
    ActorChallenge = 'prefab/player/ActorChallenge',
    /** 登录界面 */
    LoginView = 'prefab/login/LoginView',
    /** 网络提示框 */
    NetConfirmBox = 'prefab/login/NetConfirmBox',
    /** 创角界面 */
    CreateRoleView = 'prefab/login/CreateRoleView',
    /** 选服列表界面 */
    SelServerView = 'prefab/login/SelServerView',
    /** 开始游戏界面 */
    StartGameView = 'prefab/login/StartGamePanel',
    /** 账号注册界面 */
    AccountRegView = 'prefab/login/AccRegBox',
    /** 账号登录界面 */
    AccountLoginView = 'prefab/login/AccLoginBox',
    /** 主界面快捷按钮LobbyEasy */
    LobbyEasy = 'prefab/module/lobby/LobbyEasy',
    /** 游戏首次欢迎界面 */
    GameWelcomeWin = 'prefab/login/GameWelcomeWin',
    /** 游戏公告界面 */
    // GameNoticeView = 'prefab/login/LoginView',
    /** 账号登录界面 */
    ResLoading = 'prefab/login/ResLoading',
    /** 主角界面 */
    RoleView = 'prefab/role/RoleView',
    /** 角色界面win */
    RoleWin = 'prefab/role/RoleWin',
    /** 角色属性面板win */
    RoleAttrWin = 'prefab/role/RoleAttrWin',
    /** 角色界面 */
    RolePage = 'prefab/role/RolePage',
    /** 背包界面 */
    BagWin = 'prefab/module/bag/BagWin',
    /** 背包界面-背包页签 */
    BagPage = 'prefab/module/bag/BagPage',
    /** 背包扩容 */
    BagExpansionWin = 'prefab/module/bag/BagExpansionWin',
    /** 背包扩容 */
    BagOneKeyUseWin = 'prefab/module/bag/BagOneKeyUseWin',
    /** 背包界面-邮件页签 */
    MailPage = 'prefab/mail/MailPage',
    /** 背包界面-合成材料 */
    MergeMatPage = 'prefab/module/mergeMat/MergeMatPage',
    /** 邮件详情 */
    MailDetail = 'prefab/mail/MailDetail',
    /** 充值界面 */
    RechargeWin = 'prefab/recharge/RechargeWin',
    /** 充值页面 */
    RechargePage = 'prefab/recharge/RechargePage',
    /** 充值Item项 */
    RechargeItem = 'prefab/recharge/RechargeItem',
    /** 充值Vip */
    RechargeVip = 'prefab/recharge/RechargeVip',
    /** 兑换界面 */
    ExchangeWin = 'prefab/exchange/ExchangeWin',
    /** 兑换页面 */
    ExchangePage = 'prefab/exchange/ExchangePage',
    /** 充值Item项 */
    ExchangeItem = 'prefab/exchange/ExchangeItem',
    /** 物品来源面板 */
    ItemSourceWin = 'prefab/com/item/ItemSourceWin',
    /** 二次确认框 */
    ConfirmBox = 'prefab/com/msgbox/ConfirmBox',
    /** 熔炼主窗口 */
    SmeltWin = 'prefab/module/smelt/SmeltWin',
    /** 熔炼次窗口 */
    SmeltPage = 'prefab/module/smelt/SmeltPage',
    /** 装备win */
    EquipWin = 'prefab/module/equip/EquipWin',
    /** 强化次窗口 */
    StrengthPage = 'prefab/module/equip/strength/StrengthPage',
    /** 打造次窗口 */
    BuildPage = 'prefab/module/equip/buildEquip/BuildPage',

    /** 西域行商 */
    SilkRoadPage = 'prefab/module/equip/silkRoad/SilkRoadPage',
    SilkRoadSelectView = 'prefab/module/equip/silkRoad/SilkRoadSelectView',
    SilkRoadMapView = 'prefab/module/equip/silkRoad/SilkRoadMapView',
    SilkRoadReward = 'prefab/module/equip/silkRoad/SilkRoadReward',
    SilkRoadEventReward = 'prefab/module/equip/silkRoad/SilkRoadEventReward',

    /** 游历天下 */
    AdventurePage = 'prefab/module/adventure/AdventurePage',
    AdventureEventView = 'prefab/module/adventure/AdventureEventView',
    AdventureReward = 'prefab/module/adventure/AdventureReward',
    AdventureGoldDice = 'prefab/module/adventure/AdventureGoldDice',

    /** 宝石窗口 */
    GemPage = 'prefab/module/equip/gem/GemPage',
    /** 特性提升 */
    GemCompare = 'prefab/module/equip/gem/GemCompare',

    /** 强化次窗口 */
    ResonanceWin = 'prefab/module/equip/strength/ResonanceWin',
    /** 道具Tips */
    ItemTipsWin = 'prefab/com/tips/ItemTipsWin',
    /** 道具Tips自选宝箱弹框 */
    ItemTipsPickChestWin = 'prefab/com/tips/ItemTipsPickChestWin',
    /** 恭喜获得 */
    GetRewardWin = 'prefab/com/getreward/GetRewardWin',
    /** 收益包裹 */
    PackageWin = 'prefab/module/bag/PackageWin',
    /** 通用奖励展示-格子类型 */
    WinRwShow = 'prefab/com/win/WinRwShow',
    /** 首领界面 */
    BossWin = 'prefab/module/boss/BossWin',
    BossPage = 'prefab/module/boss/BossPage',
    PersonalPage = 'prefab/module/boss/PersonalPage',
    ComBossPage = 'prefab/module/boss/ComBossPage',
    BossRankList = 'prefab/module/boss/win/BossRankList',
    BossHitRank = 'prefab/module/boss/win/BossHitRank',
    BossInspireWin = 'prefab/module/boss/win/BossInspireWin',
    BossAwardPriew = 'prefab/module/boss/win/BossAwardPriew',
    WorldBossPage = 'prefab/module/worldBoss/WorldBossPage',
    WorldBossMJPage = 'prefab/module/worldBoss/WorldBossMJPage',
    WorldBossInspireWin = 'prefab/module/worldBoss/v/WorldBossInspireWin',
    WorldBossGrabWin = 'prefab/module/worldBoss/v/WorldBossGrabWin',
    WorldBossRankView = 'prefab/module/worldBoss/v/WorldBossRankView',
    WorldBossRewardPreview = 'prefab/module/worldBoss/v/WorldBossRewardPreview',
    // 烽火连城
    BeaconWarPage = 'prefab/module/beaconWar/BeaconWarPage',
    BeaconWarInspireWin = 'prefab/module/beaconWar/v/BeaconWarInspireWin',
    BeaconWarRePreWin = 'prefab/module/beaconWar/v/BeaconWarRePreWin',
    BeaconWarQuickWin = 'prefab/module/beaconWar/v/BeaconWarQuickWin',
    BeaconWarTreatWin = 'prefab/module/beaconWar/v/BeaconWarTreatWin',
    BeaconRelive = 'prefab/module/beaconWar/com/BeaconRelive',
    BeaconBossMsg = 'prefab/module/beaconWar/com/BeaconBossMsg',
    BeaconMsg = 'prefab/module/beaconWar/com/BeaconMsg',

    /** 等级提升 */
    LevelUp = 'prefab/com/LevelUp',
    /** 战力提升 */
    FvUp = 'prefab/com/FvUp',
    /** 分享到聊天 */
    ShareToChat = 'prefab/com/ShareToChat',
    /** tips */
    ShowTips = 'prefab/com/ShowTips',
    /** 聊天界面 */
    ChatWin = 'prefab/module/chat/ChatWin',
    /** 聊天表情包界面 */
    ChatEmoji = 'prefab/module/chat/ChatEmojiView',
    /** 跑马灯公告 */
    NoticeWin = 'prefab/module/chat/NoticeWin',
    /** 通用聊天控件 */
    ChatCommon = 'prefab/module/chat/ChatCommon',
    /** 战斗结算 */
    BattleVictory = 'prefab/module/battleResult/BattleVictory',
    BattleFail = 'prefab/module/battleResult/BattleFail',
    /** 道具快速使用弹框 */
    ItemQuickUseWin = 'prefab/com/item/ItemQuickUseWin',
    /** 战力细节弹框 */
    FightValueDetailWin = 'prefab/com/fightValue/FightValueDetailWin',
    /** 称号界面 */
    TitleWin = 'prefab/module/title/TitleWin',
    TitlePage = 'prefab/module/title/TitlePage',
    TitleDetail = 'prefab/module/title/TitleDetail',
    /** 打造页面的tip */
    ItemTipsBuildWin = 'prefab/module/equip/buildEquip/ItemTipsBuildWin',
    /** 装备升星界面 */
    EquipUpStarPage = 'prefab/module/equip/upStar/UpStarPage',
    /** 主城界面 */
    MainCity = 'prefab/module/maincity/MainCity',
    /** 进阶弹框 */
    GradeWin = 'prefab/module/grade/GradeWin',
    /** 进阶页 */
    GradePage = 'prefab/module/grade/GradePage',
    /** 升星选择装备 */
    UpStarSelectEquipWin = '/prefab/module/equip/upStar/UpStarSelectEquipWin',
    /** 进阶一键购买 */
    WinComQuickPay = 'prefab/module/pay/WinComQuickPay',
    /** 进阶化金 */
    GradeToGoldWin = 'prefab/module/grade/win/GradeToGoldWin',
    /** 进阶豪礼窗口 */
    GradeGiftWin = 'prefab/module/gradeGift/GradeGiftWin',
    /** 进阶豪礼页面 */
    GradeGiftPage = 'prefab/module/gradeGift/GradeGiftPage',
    /** 时装注灵 */
    GradeSoulWin = 'prefab/module/grade/win/GradeSoulWin',
    /** 进阶吞噬界面 */
    GradeGodWin = 'prefab/module/grade/win/GradeGodWin',
    /** 进阶获得奖励界面 */
    GradeGetAwardsWin = 'prefab/module/grade/win/GradeGetAwardsWin',
    /** 进阶购买提示 */
    WinAutoPayTips = 'prefab/module/pay/WinAutoPayTips',
    /** 属性加成界面 */
    AttrTips = 'prefab/com/AttrTips',
    /** 战力详情界面（扩展） */
    AttrDetailTips = 'prefab/com/AttrDetailTips',
    /** 角色时装窗口 */
    RoleSkinWin = 'prefab/module/roleskin/RoleSkinWin',
    RoleSkinCommon = 'prefab/module/roleskin/com/RoleSkinCommon',
    /** 角色时装页面 */
    RoleSkinPage = 'prefab/module/roleskin/RoleSkinPage',
    /** 角色时装套装页面 */
    RoleSkinSuitPage = 'prefab/module/roleskin/RoleSkinSuitPage',
    /** 角色活动套装页面 */
    RoleActivitySuitPage = '/prefab/module/roleskin/RoleActivitySuitPage',
    /** 角色异域套装页面 */
    RoleExoticSuitPage = '/prefab/module/roleskin/RoleExoticSuitPage',
    /** 升星结果弹窗 */
    UpStarRewardWin = '/prefab/module/equip/upStar/UpStarRewardWin',
    /** 角色技能窗口 */
    RoleSkillPage = 'prefab/module/roleSkills/RoleSkillPage',
    RSkillPage = 'prefab/module/roleSkills/RSkillPage',
    RoleMartialPage = 'prefab/module/roleSkills/martialSkill/RoleMartialPage',
    UniqueSkillPage = 'prefab/module/roleSkills/uniqueSkill/UniqueSkillPage',
    UniqueSkillTip = 'prefab/module/roleSkills/uniqueSkill/UniqueSkillPage',

    /** 角色活动套装属性 */
    RoleActivitySuitAttr = '/prefab/module/roleskin/com/RoleActivitySuitAttr',
    /** 角色时装属性 */
    RoleSkinAttr = '/prefab/module/roleskin/com/RoleSkinAttr',
    /** 角色时装套装信息 */
    RoleSkinSuitInfo = '/prefab/module/roleskin/com/RoleSkinSuitInfo',
    /** 角色时装套装部件 */
    RoleSkinSuitItem = '/prefab/module/roleskin/com/RoleSkinSuitItem',
    /** 角色时装套装部件详情 */
    RoleSuitPartWin = '/prefab/module/roleskin/com/RoleSuitPartWin',
    /** 竞技场win */
    ArenaWin = 'prefab/module/arena/ArenaWin',
    /** 竞技场 */
    ArenaPage = 'prefab/module/arena/ArenaPage',
    /** 竞技场排名奖励界面 */
    ArenaRankRewardView = 'prefab/module/arena/ArenaRankRewardView',
    /** 排位赛 */
    RankMatchPage = 'prefab/module/arena/rankMatch/v/RankMatchPage',
    /** 排位赛-前三名Item */
    RankMatchHeadItem = 'prefab/module/arena/rankMatch/com/RankMatchHeadItem',
    /** 排位赛奖励窗口 */
    RankMatchAwardWin = 'prefab/module/arena/rankMatch/v/RankMatchAwardWin',
    /** 排位赛排名奖励界面 */
    RankMatchAwardView = 'prefab/module/arena/rankMatch/v/RankMatchAwardView',
    /** 排位赛奖励-Item */
    RankMatchAwardItem = 'prefab/module/arena/rankMatch/com/RankMatchAwardItem',
    /** 排位赛奖励-胜场奖励 */
    RankMatchAwardBottomWin = 'prefab/module/arena/rankMatch/com/RankMatchAwardBottomWin',
    /** 排位赛奖励-段位奖励 */
    RankMatchAwardBottomSegme = 'prefab/module/arena/rankMatch/com/RankMatchAwardBottomSegme',
    /** 排位赛战报 */
    RankMatchReportWin = 'prefab/module/arena/rankMatch/v/RankMatchReportWin',
    /** 排位赛排行榜 */
    RankMatchRankWin = 'prefab/module/arena/rankMatch/v/RankMatchRankWin',
    /** 排位赛-匹配对决 */
    RankMatchDuel = 'prefab/module/arena/rankMatch/v/RankMatchDuel',
    /** 排位赛-赛季重置 */
    RankMatchReset = 'prefab/module/arena/rankMatch/v/RankMatchReset',
    /** 排位赛排行榜奖励界面 */
    RankMatchRankView = 'prefab/module/arena/rankMatch/v/RankMatchRankView',
    /** 竞技场排行榜界面 */
    ArenaRankListView = 'prefab/module/arena/ArenaRankListView',
    /** 竞技场结算界面 */
    BattleRewardView = 'prefab/module/battleResult/BattleRewardView',
    /** 技能详情页面 */
    TipsSkillWin = 'prefab/com/tips/TipsSkillWin',
    // 官职的win
    RoleArmyOfficialPage = 'prefab/module/roleOfficial/RoleArmyOfficialPage',
    RoleOfficialPage = 'prefab/module/roleOfficial/official/RoleOfficialPage',
    RoleArmyLevelPage = 'prefab/module/roleOfficial/armyLevel/RoleArmyLevelPage',
    /** 官职奖励界面 */
    RoleOfficialRewardWin = 'prefab/module/roleOfficial/official/RoleOfficialRewardWin',
    /** 官职详细界面 */
    RoleOfficialInfoView = 'prefab/module/roleOfficial/official/RoleOfficialInfoView',

    // 军衔预览
    ArmyPreviewTip = 'prefab/module/roleOfficial/armyLevel/ArmyPreviewTip',
    /** 激活绝学tip */
    ActiveSkillTip = 'prefab/module/roleSkills/uniqueSkill/ActiveSkillTip',
    /** 军衔提升 */
    ArmyLevelUpTip = 'prefab/module/roleOfficial/armyLevel/ArmyLevelUpTip',
    /** 玩法说明 */
    DescWinTip = 'prefab/com/desc/DescWinTip',
    /** 材料副本win */
    MaterialWin = 'prefab/module/material/MaterialWin',
    /** 材料副本page */
    MaterialPage = 'prefab/module/material/MaterialPage',
    /** 组队副本page */
    TeamPage = 'prefab/module/material/team/TeamPage',
    /** 组队阵容界面 */
    TeamWin = 'prefab/module/material/team/TeamWin',
    /** 组队阵容界面 */
    TeamView = 'prefab/module/material/team/TeamView',
    /** 队伍item */
    TeamItem = 'prefab/module/material/team/com/TeamItem',
    /** 成员item */
    TeamMemberItem = 'prefab/module/material/team/com/TeamMemberItem',
    /** 邀请玩家界面 */
    InvitePlayerWin = 'prefab/module/material/team/InvitePlayerWin',
    /** 邀请确认框 */
    InvitationBox = 'prefab/module/material/team/InvitationBox',
    /** 组队阵容预览界面 */
    TeamPlanPreView = 'prefab/module/material/team/TeamPlanPreView',
    /** 组队奖励界面 */
    TeamRewardWin = 'prefab/module/material/team/TeamRewardWin',
    /** 邀请玩家界面 */
    InvitePlayerView = 'prefab/module/material/team/InvitePlayerView',
    /** 我的队伍 */
    MyTeamView = 'prefab/module/material/team/MyTeamView',
    /** 队伍列表 */
    TeamListView = 'prefab/module/material/team/TeamListView',
    /** 材料副本view */
    MaterialView = 'prefab/module/material/MaterialView',
    /** 材料副本奖励预览 */
    MaterialRewardScanWin = 'prefab/module/material/MaterialRewardScanWin',
    /** 仙术view */
    TheurgyView = 'prefab/module/material/TheurgyView',
    /** GeneralCombo */
    GeneralCombo = 'prefab/module/general/com/GeneralCombo',
    /** 武将 */
    GeneralWin = 'prefab/module/general/GeneralWin',
    /** 武将页签 */
    GeneralPage = 'prefab/module/general/GeneralPage',
    /** 武将-信息页 */
    InfoPanel = 'prefab/module/general/InfoPanel',
    /** 武将-升级页 */
    LevelUpPanel = 'prefab/module/general/LevelUpPanel',
    /** 武将-升阶页 */
    GradeUpPanel = 'prefab/module/general/GradeUpPanel',
    /** 武将-觉醒页 */
    AwakenPanel = 'prefab/module/general/AwakenPanel',
    /** 武将-装备页 */
    GEquipPanel = 'prefab/module/general/GEquipPanel',
    /** 武将-技能页 */
    GSkillPanel = 'prefab/module/general/gSkill/GSkillPanel',
    /** 公共部分 */
    GeneralEntity = 'prefab/module/general/com/GeneralEntity',
    GeneralItem = 'prefab/module/general/com/GeneralItem',
    GeneralHead = 'prefab/module/general/com/GeneralHead',
    GeneralRewardWin = 'prefab/module/general/com/GeneralRewardWin',
    GeneralChooseWin = 'prefab/module/general/com/GeneralChooseWin',
    GEquipItem = 'prefab/module/general/com/GEquipItem',
    /** 升品页签 */
    QualityUpPage = 'prefab/module/general/qualityUp/QualityUpPage',
    QualityUpPreview = 'prefab/module/general/qualityUp/QualityUpPreview',
    QualityUpSucess = 'prefab/module/general/qualityUp/QualityUpSucess',
    QualityOnekeyUp = 'prefab/module/general/qualityUp/QualityOneKeyUp',
    /** 武将-布阵 */
    PlanWin = 'prefab/module/general/plan/PlanWin',
    PlanPage = 'prefab/module/general/plan/PlanPage',
    TeamPlanPage = 'prefab/module/general/plan/TeamPlanPage',
    PlanPos = 'prefab/module/general/plan/PlanPos',
    /** 武将-皮肤 */
    GskinWin = 'prefab/module/general/gskin/GskinWin',
    GskinPage = 'prefab/module/general/gskin/GSkinPage',
    GeneralSkinEntity = 'prefab/module/general/com/GeneralSkinEntity',
    /** 武将-升阶-选择 */
    GradeUpChooseWin = 'prefab/module/general/gradeUp/GradeUpChooseWin',
    /** 武将技能详情页面 */
    GeneralSkillWin = 'prefab/module/general/gradeUp/GeneralSkillWin',
    /** 武将-技能-选择 */
    GSkillChooseWin = 'prefab/module/general/gSkill/GSkillChooseWin',
    /** 武将-技能-回收 */
    GSkillRecycleWin = 'prefab/module/general/gSkill/GSkillRecycleWin',
    /** 武将-技能-推荐 */
    GSkillRecomWin = 'prefab/module/general/gSkill/GSkillRecomWin',
    /** 武将装备展示 */
    GEquipTipsWin = 'prefab/module/general/gEquip/GEquipTipsWin',
    /** 羁绊 */
    GFetters = 'prefab/module/general/gFetters/GFetters',
    /** 武将图鉴 */
    GBookWin = 'prefab/module/general/gBook/GBookWin',
    GBookPage = 'prefab/module/general/gBook/GBookPage',
    GBookDetailWin = 'prefab/module/general/gBook/GBookDetailWin',
    GBookDetailPage = 'prefab/module/general/gBook/GBookDetailPage',
    /** 武将合成 */
    GComposePage = 'prefab/module/general/gBook/GComposePage',
    /** 武将重生 */
    GRebornPage = 'prefab/module/general/gReborn/GRebornPage',
    GRebornPanel = 'prefab/module/general/gReborn/GRebornPanel',
    GRebornChooseWin = 'prefab/module/general/gReborn/GRebornChooseWin',
    /** 武将遣散 */
    GDisbandPanel = 'prefab/module/general/gReborn/GDisbandPanel',
    /** 日常 */
    DailyWin = 'prefab/module/daily/DailyWin',
    /** 押镖 */
    EscortPage = 'prefab/module/escort/EscortPage',
    RobbedWin = 'prefab/module/escort/RobbedWin',
    RobWin = 'prefab/module/escort/RobWin',
    ChooseBoardWin = 'prefab/module/escort/ChooseBoardWin',
    EscortRewardWin = 'prefab/module/escort/EscortRewardWin',
    EscortItem = 'prefab/module/escort/com/EscortItem',
    LostItem = 'prefab/module/escort/com/LostItem',
    /** 功能预告 */
    FuncPreviewPage = 'prefab/module/funcPreview/FuncPreviewPage',
    FuncOpenWin = 'prefab/module/funcPreview/FuncOpenWin',

    /** Vip win */
    VipWin = 'prefab/module/vip/VipWin',
    /** 奖励展示弹窗 */
    WinReward = 'prefab/com/win/WinReward',
    /** vip特权提升窗口 */
    VipContentTipWin = 'prefab/module/vip/VipContentTipWin',
    /** vip 升级弹窗 */
    VipUpdateWin = 'prefab/module/vip/VipUpdateWin',
    /** vip 和充值界面的 父级视图win */
    VipSuperWin = 'prefab/module/vip/VipSuperWin',
    /** vip view */
    VipView = 'prefab/module/vip/VipView',
    BossBigHp = 'prefab/module/worldBoss/BossBigHp',
    /** 拼点弹窗 */
    RollFrame = 'prefab/module/worldBoss/RollFrame',
    /** 护盾弹窗 */
    ShieldFrame = 'prefab/module/worldBoss/ShieldFrame',

    /** 副本UI，格式：FuBen_xx， xx对应的地图配置表的副本类型 */
    /** 世界boss */
    FuBen_1 = 'prefab/module/worldBoss/WorldBoss',
    /** 烽火连城副本 */
    FuBen_2 = 'prefab/module/beaconWar/BeaconWar',

    /** 商城界面win */
    ShopWin = 'prefab/module/shop/ShopWin',
    /** 商城界面view */
    ShopView = 'prefab/module/shop/ShopView',
    /** 折扣商城page */
    DiscountShopPage = 'prefab/module/shop/DiscountShopPage',
    /** 神秘商城page */
    SecretShopPage = 'prefab/module/shop/SecretShopPage',
    /** 基础的战斗面板 */
    BattlePanel = 'prefab/battle/BattlePanel',
    /** 世界boss战斗面板 */
    BattleWorldBoss = 'prefab/battle/com/BattleWorldBoss',
    /** 折扣商城page */
    ExchangeShopPage = 'prefab/module/shop/ExchangeShopPage',
    /** 神秘商城page */
    UnitShopPage = 'prefab/module/shop/UnitShopPage',
    /** 折扣商城page */
    ActiveShopPage = 'prefab/module/shop/ActiveShopPage',
    /** 购买物品弹窗 */
    WinQuickPay = 'prefab/module/pay/WinQuickPay',
    /** 挂机 */
    OnHookWin = 'prefab/module/onHook/OnHookWin',
    OnHoolTips = 'prefab/module/onHook/OnHoolTips',
    /** 飞道具 */
    FlyItem = 'prefab/module/onHook/FlyItem',
    /** 关卡win */
    GameLevelWin = 'prefab/module/gameLevel/GameLevelWin',
    /** 关卡page */
    GameLevelPage = 'prefab/module/gameLevel/GameLevelPage',
    /** 关卡奖励窗口 */
    GamePassWin = 'prefab/module/gamePass/GamePassWin',
    /** 关卡奖励视图 */
    GamePassView = 'prefab/module/gamePass/com/GamePassView',
    /** 引导 */
    GuideUI = 'prefab/com/guide/GuideUI',

    // 颗粒奖励部分
    BattleSettlePartReward = 'prefab/module/battleResult/ex/BattleRewardEx',
    // 颗粒竞技场
    BattleSettlePartArena = 'prefab/module/battleResult/ex/BattleArenaEx',
    // 颗粒失败跳转
    BattleSettlePartFail = 'prefab/module/battleResult/ex/BattleFailEx',
    // 颗粒文本部分（分为两个Label ，一个普通白色字体，均为居中对齐）
    BattleSettlePartText = 'prefab/module/battleResult/ex/BattleTextEx',
    // 颗粒文本部分（其他样式，主要针对Label非居中对齐）
    BattleSettlePartBgText = 'prefab/module/battleResult/ex/BattleBgTextEx',
    // 颗粒表情图标
    BattleSettlePartEmoji = 'prefab/module/battleResult/ex/BattleEmojiEx',
    // 颗粒排位赛战斗结算
    BattleRankMatchEx = 'prefab/module/battleResult/ex/BattleRankMatchEx',
    /** 战斗结算 */
    BattleSettleWin = 'prefab/module/battleResult/BattleSettleWin',

    /** 关卡新章节开启 */
    GameLevelNewChapterView = 'prefab/module/gameLevel/GameNewChapterView',
    /** 常驻排行榜 */
    RankListWin = 'prefab/module/rankList/RankListWin',
    RankListLocalPage = 'prefab/module/rankList/RankListLocalPage',
    /** 实名认证弹窗 */
    IdentitykBox = 'prefab/com/msgbox/IdentitykBox',
    RealNameWin = 'prefab/login/RealNameWin',

    /** 虎符官印 win */
    SealAmuletWin = 'prefab/module/sealAmulet/SealAmuletWin',
    /** 虎符官印page */
    SealAmuletPage = 'prefab/module/sealAmulet/SealAmuletPage',
    /** 虎符官印公共部分 */
    SealAmuletView = 'prefab/module/sealAmulet/SealAmuletView',
    /** 官职升级 */
    SealAmuletUpWin = 'prefab/module/sealAmulet/SealAmuletUpWin',
    /** 虎符官印升星界面 */
    SealAmuletStarDetailView = 'prefab/module/sealAmulet/SealAmuletStarDetailView',
    /** 虎符官印升级界面 */
    SealAmuletGradeDetailView = 'prefab/module/sealAmulet/SealAmuletGradeDetailView',
    /** 虎符官印升级界面 */
    SealAmuletGradeContentView = 'prefab/module/sealAmulet/SealAmuletGradeContentView',
    /** 虎符官印淬炼界面 */
    SealAmuletQualityDetailView = 'prefab/module/sealAmulet/SealAmuletQualityDetailView',
    /** star content */
    SealAmuletStarContentView = 'prefab/module/sealAmulet/SealAmuletStarContentView',
    /** quality content */
    SealAmuletQualityContentView = 'prefab/module/sealAmulet/SealAmuletQualityContentView',
    /** 虎符官印属性展示 */
    SealAmuletTipWin = 'prefab/module/sealAmulet/SealAmuletTipWin',
    /** 红颜界面 */
    BeautyWin = 'prefab/module/beauty/BeautyWin',
    /** 红颜页签 */
    BeautyPage = 'prefab/module/beauty/v/BeautyPage',
    /** 红颜tips视图 */
    BeautyTipsView = 'prefab/module/beauty/v/BeautyTipsView',
    /** 虎符威慑战斗开场 */
    ROfficialBattle = 'prefab/battle/StartPanel/ROfficialBattle',
    /** 组队副本开场动画面板 */
    TameStartPanel = 'prefab/battle/StartPanel/TameStartPanel',

    /** 系统设置 */
    SettingPage = 'prefab/module/setting/SettingPage',
    SettingWin = 'prefab/module/setting/SettingWin',
    ModifyNamePage = 'prefab/module/setting/ModifyNamePage',

    /** 头像头像框 */
    HeadPage = 'prefab/module/head/HeadPage',
    HeadInfoView = 'prefab/module/head/HeadInfoView',
    /** 属性信息简略弹窗显示 */
    AttrSimpleWin = 'prefab/com/AttrSimpleWin',
    NewPlotPanel = 'prefab/module/newplot/NewPlotPanel',
    PlotIkonPanel = 'prefab/module/newplot/PlotIkonPanel',

    /** 好友 */
    FriendWin = 'prefab/module/friend/FriendWin',
    FriendChatWin = 'prefab/module/friend/FriendChatWin',
    MyFriendApplyView = 'prefab/module/friend/MyFriendApplyView',
    MyFriendView = 'prefab/module/friend/MyFriendView',
    FriendAddWin = 'prefab/module/friend/FriendAddWin',
    FriendPage = 'prefab/module/friend/FriendPage',

    /** 博物志 */
    CollectionBookWin = 'prefab/module/collectionBook/CollectionBookWin',
    /** 博物志-奖励预览 */
    CollectionBookRw = 'prefab/module/collectionBook/v/CollectionBookRw',
    /** 博物志-见闻总览 */
    CollectionBookInfo = 'prefab/module/collectionBook/v/CollectionBookInfo',
    /** 博物志-生涯 */
    CollectionBookCareer = 'prefab/module/collectionBook/v/CollectionBookCareer',
    CollectionPicDetailsWin = 'prefab/module/collectionBook/v/CollectionPicDetailsWin',
    CollectionUpDetailsWin = 'prefab/module/collectionBook/v/CollectionUpDetailsWin',
    CollectionAttrUpWin = 'prefab/module/collectionBook/v/CollectionAttrUpWin',
    /** 博物志-人物 */
    CollectionBookPerson = 'prefab/module/collectionBook/v/CollectionBookPerson',
    /** 博物志-奇物 */
    CollectionBookWonder = 'prefab/module/collectionBook/v/CollectionBookWonder',
    /** 世家系统 */
    FamilyHomePage = 'prefab/module/family/FamilyHomePage',
    FamilyWin = 'prefab/module/family/FamilyWin',
    /** 世家-世家 */ /** 世家-成员 */
    FamilyFamilyPage = 'prefab/module/family/FamilyFamilyPage',
    FamilyMemberPage = 'prefab/module/family/FamilyMemberPage',
    FamilyDrillGroundPage = 'prefab/module/family/FamilyDrillGround/FamilyDrillGroundPage',
    FamilyTotemPage = 'prefab/module/family/FamilyTotem/FamilyTotemPage',
    /** 世家-事务 */
    FamilyTaskWin = 'prefab/module/family/FamilyTaskWin',
    FamilyTaskPage = 'prefab/module/family/FamilyTaskPage',
    /** 世家 -设置协助 */
    FamilySetAssistTip = 'prefab/module/family/FamilySetAssistTip',
    /** 世家 一键派遣 */
    FamilyAutoDispathTip = 'prefab/module/family/FamilyAutoDispathTip',
    /** 世家 事务等级提升 */
    FamilyUpTipsWin = 'prefab/module/family/FamilyUpTipsWin',
    /** 世家点击tip */
    FamilyLevelTips = 'prefab/module/family/FamilyLevelTips',

    /** ------------------------------以下是活动类的，非活动类的在上面加吧--------------------------------- */
    // 活动模板
    ActivityWin = 'prefab/module/activity/ActivityWin',
    // 每日签到
    DaySigPage = 'prefab/module/activity/module/daySign/DaySignPage',
    DaySignRe = 'prefab/module/activity/module/daySign/DaySignRe',
    /** 武将招募 */
    GeneralRecruitWin = 'prefab/module/activity/module/generalRecruit/GeneralRecruitWin',
    GeneralRecruitPage = 'prefab/module/activity/module/generalRecruit/GeneralRecruitPage',
    RandomLogTip = 'prefab/module/activity/module/generalRecruit/RandomLogTip',
    GeneralAwardTip = 'prefab/module/activity/module/generalRecruit/GeneralAwardTip',
    GeneralWishTip = 'prefab/module/activity/module/generalRecruit/GeneralWishTip',
    /** 武将招募 酒馆 */
    GeneralStorePage = 'prefab/module/activity/module/generalRecruit/GeneralStorePage',
    GeneralRecRewardWin = 'prefab/module/activity/module/generalRecruit/GeneralRecRewardWin',
    GeneralAutoBuyTip = 'prefab/module/activity/module/generalRecruit/GeneralAutoBuyTip',
    /** 族长特权 */
    FamilyPowerTip = 'prefab/module/family/FamilyPowerTip',
    /** 修改世家名称 宣言 */
    FamilyModifyTip = 'prefab/module/family/FamilyModifyTip',
    /** 俸禄 宣言 */
    FamilyAwardTip = 'prefab/module/family/FamilyAwardTip',
    /** 世家-试炼副本 */
    FamilyTrialAwardTip = 'prefab/module/family/FamilyTrial/FamilyTrialAwardTip',
    /** 世家-红包tip */
    FamilyTrialRedPackTip = 'prefab/module/family/FamilyTrial/FamilyTrialRedPackTip',

    /** 世家-族长争夺 */
    FamilyPatriarchWin = 'prefab/module/family/FamilyPatriarch/FamilyPatriarchWin',
    FamilyPatriarchPage = 'prefab/module/family/FamilyPatriarch/FamilyPatriarchPage',
    /** 世家-伤害排行 */
    FamilyPatriarchRankPage = 'prefab/module/family/FamilyPatriarch/FamilyPatriarchRankPage',
    /** 世家-试炼副本 */
    FamilyTrialCopyWin = 'prefab/module/family/FamilyTrial/FamilyTrialCopyWin',
    FamilyTrialCopyPage = 'prefab/module/family/FamilyTrial/FamilyTrialCopyPage',
    FamilyTrialRankTip = 'prefab/module/family/FamilyTrial/FamilyTrialRankTip',

    /** 在线奖励 */
    OnlineRewardPage = 'prefab/module/activity/module/onlineReward/OnlineRewardPage',
    /** 摇钱树 */
    CashCowPage = 'prefab/module/activity/module/cashCow/CashCowPage',
    /** 摇钱树购买弹窗 */
    CashCowBuyWin = 'prefab/module/activity/module/cashCow/CashCowBuyWin',
    /** 仙装win */
    RoleSpecialSuitWin = 'prefab/module/roleskin/RoleSpecialSuitWin',
    /** 仙装page */
    RoleSpecialSuitPage = 'prefab/module/roleskin/RoleSpecialSuitPage',
    /** 华服属性界面 */
    RoleSkinSpecialSuitInfo = '/prefab/module/roleskin/com/RoleSkinSpecialSuitInfo',
    /** 华服首次激活穿戴界面 */
    RoleSpecialCollectWin = '/prefab/module/roleskin/com/RoleSpecialCollectWin',

    /** 炼体窗口 */
    RoleExerciseWin = '/prefab/module/roleExercise/RoleExerciseWin',
    /** 炼体分页 */
    RoleExercisePage = '/prefab/module/roleExercise/RoleExercisePage',

    /** 摇钱树概率 */
    CashCowRateWin = 'prefab/module/activity/module/cashCow/CashCowRateWin',
    /** 等级、战力等的奖励 */
    StageRewardPage = 'prefab/module/activity/module/stageReward/StageRewardPage',
    /** 三国探险 */
    FBExplorePage = 'prefab/module/fbExplore/FBExplorePage',
    /** 三国探险-宝石 */
    FBExploreView = 'prefab/module/fbExplore/v/FBExploreView',
    /** 三国探险-台子 */
    FBExploreTai = 'prefab/module/fbExplore/com/FBExploreTai',
    /** 三国探险-排行 */
    FBExploreRank = 'prefab/module/fbExplore/v/FBExploreRank',
    /** 三国探险-战报 */
    FBExploreReport = 'prefab/module/fbExplore/v/FBExploreReport',
    /** 三国探险-重置 */
    FBExploreReset = 'prefab/module/fbExplore/FBExploreReset',

    /** 日常周常任务 资源找回 */
    /** * 日常任务pagePath */
    DailyWeeklyTaskPage = 'prefab/module/dailyTask/DailyWeeklyTaskPage',
    ResRecoveryPage = 'prefab/module/dailyTask/ResRecoveryPage',
    ResRecoveryView = 'prefab/module/dailyTask/ResRecoveryView',
    /** 资源找回购买界面 */
    ResRecoveryBuyWin = 'prefab/module/dailyTask/ResRecoveryBuyWin',
    /** 物品预览 */
    ComItemsScanWin = 'prefab/module/dailyTask/ComItemsScanWin',

    Base_Root = 'prefab/base/Root',
    Base_SceneMap = 'prefab/base/SceneMap',
    Com_AttrDetailItem = 'prefab/com/AttrDetailItem',
    Com_FightValue = 'prefab/com/fightValue/FightValue',
    Com_Item_ItemFromItem = 'prefab/com/item/ItemFromItem',
    Com_Item_ItemIcon = 'prefab/com/item/ItemIcon',
    Com_Reddot_RedDot = 'prefab/com/reddot/RedDot',
    Com_Tips_Content_ItemTipsAttrContent = 'prefab/com/tips/content/ItemTipsAttrContent',
    Com_Tips_Content_ItemTipsAvatarContent = 'prefab/com/tips/content/ItemTipsAvatarContent',
    Com_Tips_Content_ItemTipsEquipContent = 'prefab/com/tips/content/ItemTipsEquipContent',
    Com_Tips_Content_ItemTipsGeneralContent = 'prefab/com/tips/content/ItemTipsGeneralContent',
    Com_Tips_Content_ItemTipsPickChestContent = 'prefab/com/tips/content/ItemTipsPickChestContent',
    Com_Tips_Content_ItemTipsRandomChestContent = 'prefab/com/tips/content/ItemTipsRandomChestContent',
    Module_Activity_ActivityButton = 'prefab/module/activity/ActivityButton',
    Module_Arena_ArenaNormalItem = 'prefab/module/arena/ArenaNormalItem',
    Module_Arena_ArenaTopItem = 'prefab/module/arena/ArenaTopItem',
    Module_Bag_BagItemIcon = 'prefab/module/bag/BagItemIcon',
    Module_BattleResult = 'prefab/module/battleResult/',
    Module_BattleResult_BattleResultCommonView = 'prefab/module/battleResult/BattleResultCommonView',
    Module_Beauty_Com_BeautyActive = 'prefab/module/beauty/com/BeautyActive',
    Module_Beauty_Com_BeautyHead = 'prefab/module/beauty/com/BeautyHead',
    Module_Beauty_Com_BeautySkill = 'prefab/module/beauty/com/BeautySkill',
    Module_Chat_ChatCopyTip = 'prefab/module/chat/ChatCopyTip',
    Module_Chat_ChatDefaultIem = 'prefab/module/chat/ChatDefaultIem',
    Module_Chat_ChatDefaultMeIem = 'prefab/module/chat/ChatDefaultMeIem',
    Module_Chat_ChatInputView = 'prefab/module/chat/ChatInputView',
    Module_Chat_ChatMenuBar = 'prefab/module/chat/ChatMenuBar',
    Module_Chat_ChatSysItem = 'prefab/module/chat/ChatSysItem',
    Module_Equip_Gem_GemEquipItem = 'prefab/module/equip/gem/GemEquipItem',
    Module_Equip_Strength_StrengthItem = 'prefab/module/equip/strength/StrengthItem',
    Module_GameLevel = 'prefab/module/gameLevel/',
    Module_GameLevel_GameLevelInfoLeft = 'prefab/module/gameLevel/GameLevelInfoLeft',
    Module_General_Com_GEquipItem = 'prefab/module/general/com/GEquipItem',
    Module_General_Com_GSkillItem = 'prefab/module/general/com/GSkillItem',
    Module_General_Com_GeneralHead = 'prefab/module/general/com/GeneralHead',
    Module_General_Com_GeneralPlanHead = 'prefab/module/general/com/GeneralPlanHead',
    Module_General_Plan_PlanPos = 'prefab/module/general/plan/PlanPos',
    Module_Grade_Com_GradeSkillItem = 'prefab/module/grade/com/GradeSkillItem',
    Module_Grade_GradeAvatarInfoPanel = 'prefab/module/grade/GradeAvatarInfoPanel',
    Module_Grade_GradeUpInfoPanel = 'prefab/module/grade/GradeUpInfoPanel',
    Module_Grade_GradeEquipInfoPanel = 'prefab/module/grade/GradeEquipInfoPanel',
    Module_Grade_GradeSkinInfoPanel = 'prefab/module/grade/GradeSkinInfoPanel',
    Module_Lobby_LobbyNewPlayer = 'prefab/module/lobby/LobbyNewPlayer',
    Module_Lobby_LobbyUI = 'prefab/module/lobby/LobbyUI',
    Module_Lobby_LobbyUIBottom = 'prefab/module/lobby/LobbyUIBottom',
    Module_Lobby_LobbyUILeft = 'prefab/module/lobby/LobbyUILeft',
    Module_Lobby_LobbyUIRight = 'prefab/module/lobby/LobbyUIRight',
    Module_Lobby_LobbyUITop = 'prefab/module/lobby/LobbyUITop',
    Module_RoleOfficial_Official_RoleOfficialItemIcon = 'prefab/module/roleOfficial/official/RoleOfficialItemIcon',
    Module_SealAmulet_SealAmuletItem = 'prefab/module/sealAmulet/SealAmuletItem',
    Module_SealAmulet_SealAmuletQualityItem = 'prefab/module/sealAmulet/SealAmuletQualityItem',
    Module_SealAmulet_SealAmuletStarItem = 'prefab/module/sealAmulet/SealAmuletStarItem',
    Module_Shop_SecretShopItem = 'prefab/module/shop/SecretShopItem',
    Module_Vip_VipContentItem = 'prefab/module/vip/VipContentItem',
    Module_Vip_VipInfoView = 'prefab/module/vip/VipInfoView',
    /** 等级战力通行证 */
    GeneralPassPage = 'prefab/module/activity/module/generalPass/GeneralPassPage',
    CdKeyPage = 'prefab/module/activity/module/cdKey/CdKeyPage',
    /** 全民福利win */
    WelfareWin = 'prefab/module/activity/module/generalPass/WelfareWin',
    /** buff列表界面，状态显示 */
    BuffListWin = 'prefab/module/rankList/BuffListWin',
    /** 世界等级 */
    WorldLevelWin = 'prefab/module/rankList/WorldLevelWin',
    /** 军师 */
    AdviserWin = 'prefab/module/adviser/AdviserWin',
    /** 军师 */
    AdviserPage = 'prefab/module/adviser/v/AdviserPage',
    /** 专精 */
    AdviserMasteryPage = 'prefab/module/adviser/v/AdviserMasteryPage',
    /** 专精Item */
    AdviserMasteryItem = 'prefab/module/adviser/com/AdviserMasteryItem',

    /** 华容道 */
    HuarongdaoPage = 'prefab/module/huarongdao/HuarongdaoPage',
    HuarongdaoMapView = 'prefab/module/huarongdao/HuarongdaoMapView',
    HuarongdaoHandlerView = 'prefab/module/huarongdao/HuarongdaoHandlerView',
    HuarongdaoSupport = 'prefab/module/huarongdao/HuarongdaoSupport',
    HuarongdaoGiftBuy = 'prefab/module/huarongdao/HuarongdaoGiftBuy',
    HuarongdaoRecord = 'prefab/module/huarongdao/HuarongdaoRecord',
    HuarongdaoResult = 'prefab/module/huarongdao/HuarongdaoResult',
    HuarongdaoBulletChat = 'prefab/module/huarongdao/HuarongdaoBulletChat',
    HuarongdaoCountDown = 'prefab/module/huarongdao/HuarongdaoCountDown',
    HuarongdaoTips = 'prefab/module/huarongdao/HuarongdaoTips',
}
