/* eslint-disable semi */
/* eslint-disable no-trailing-spaces */
/* eslint-disable spaced-comment */
/* eslint-disable quotes */
/* eslint-disable indent */
/* eslint-disable no-tabs */
/* eslint-disable @typescript-eslint/explicit-member-accessibility */
export class RoleMD {
	static AttrType = {
		1: "Hp", //生命
		2: "Atk", //攻击
		3: "Def", //防御
		4: "Hit", //命中
		5: "Avd", //闪避
		6: "Cri", //暴击
		7: "ACri", //防暴击
		8: "Speed", //速度
		9: "Atk1", //无视防御
		10: "Def1", //减免无视
		11: "Atk2", //伤害加深
		12: "Def2", //伤害减少
		13: "Atk3", //伤害增加%
		14: "Def3", //伤害减少%
		15: "Atk4", //暴击伤害增加
		16: "Def4", //暴击伤害减少
		17: "Atk5", //致命一击概率增加
		18: "Def5", //致命一击概率减少
		19: "Atk6", //PVP伤害增加(万分比)
		20: "Def6", //VP伤害减少(万分比)
		21: "Atk7", //PVE伤害增加(万分比)
		22: "Def7", //PVE伤害减少(万分比)
		23: "ExtraHurt", //额外伤害
		24: "Atk8", //仙击概率增加
		25: "Def8", //仙击概率减少
		101: "Hit_Real", //真实命中
		102: "Cri_Real", //真实暴击
		103: "AtkGod", //神击概率增加
		104: "DefGod", //神击概率减少
		1001: "Hp_P", //生命
		1002: "Atk_P", //攻击
		1003: "Def_P", //防御
		1004: "Hit_P", //命中
		1005: "Avd_P", //闪避
		1006: "Cri_P", //暴击
		1007: "ACri_P", //防暴击
		1008: "Speed_P", //速度
		1009: "Atk1_P", //无视防御
		1010: "Def1_P", //减免无视
		1011: "Atk2_P", //伤害加深
		1012: "Def2_P", //伤害减少
		1013: "Atk3_P", //伤害增加%
		1014: "Def3_P", //伤害减少%
		1015: "Atk4_P", //暴击伤害增加
		1016: "Def4_P", //暴击伤害减少
		1017: "Atk5_P", //致命一击概率增加
		1018: "Def5_P", //致命一击概率减少
		1019: "Atk6_P", //PVP伤害增加(万分比)
		1020: "Def6_P", //VP伤害减少(万分比)
		1021: "Atk7_P", //PVE伤害增加(万分比)
		1022: "Def7_P", //PVE伤害减少(万分比)
		1023: "ExtraHurt_P", //额外伤害
		1024: "Atk8_P", //仙击概率增加
		1025: "Def8_P", //仙击概率减少
		1101: "Hit_Real_P", //真实命中
		1102: "Cri_Real_P", //真实暴击
		1103: "AtkGod_P", //神击概率增加
		1104: "DefGod_P", //神击概率减少
		2503: "AccountId", //帐号ID
		2505: "ChannelId", //用户所属于的渠道
		2507: "AreaName", //服务器名称
		2508: "CreateAreaId", //创建区编号
		2509: "LoginAreaId", //登录区编号
		2510: "ShowAreaId", //显示区编号
		2511: "FightAreaId", //战区编号
		2513: "LogoutTime", //用户离线时间
		2515: "LastDay", //最后一次登录天：用于onDayChange 计算
		2516: "LastWeek", //最后一次登周：用于onWeekChange 计算
		2517: "LastMonth", //最后一次登月：用于onMonthChange 计算
		2519: "DayOnlineTime", //今日在线时间
		2521: "LoginDay", //累计登录天数
		2523: "LoginDayInMonth", //当月累计登录天数
		2524: "Level", //人物等级
		2525: "Nick", //昵称
		2526: "Sex", //性别
		2527: "HeadIcon", //用户头像
		2528: "FightValue", //战力值
		2529: "HeadFrame", //用户头像框
		2530: "Title", //用户称号
		2531: "PlayerSkin", //玩家形象
		2532: "ShowId", //玩家的展示形象
		2533: "IsOnline", //是否在线
		2535: "AutoFight", //是否自动战斗
		2536: "ChargeRmb", //共充值多少rmb，分
		2539: "LineUpId", //目前上阵的阵容编号
		2540: "Map_X", //地图所在的坐标x
		2541: "Map_Y", //地图所在的坐标Y
		2542: "Map_StartMoveTime", //开始移动时间
		2549: "ChangeNickTimes", //修改名字的次数
		2550: "ChangeNickCd", //下次修改名字的时间
		2553: "ArmyLevel", //军衔阶级
		2554: "MonthCard", //月卡
		2556: "ArmyStar", //军衔星数
		2557: "Stage", //通关关卡
		2559: "RealNameRealAuth", //实名认证防沉迷状态
		2560: "VipLevel", //vip等级
		2563: "Recharge", //总充值额度
		2564: "RechargeToday", //今日充值额度
		2565: "RechargeMonth", //当月充值额度
		2566: "RechargeTimes", //充值次数记录
		2568: "Welcome", //是否打开过欢迎界面
		2570: "GradeHorse", //坐骑幻化id
		2571: "GradeWing", //羽翼幻化id
		2572: "GradeWeapon", //光武幻化id
		2573: "GradeSuitId", //幻化套装id
		2574: "GradePet", //萌宠幻化id
		2600: "ArenaTimes", //竞技场挑战次数
		2601: "ArenaNextTime", //竞技场挑战下次增加时间(秒)
		2602: "ArenaRank", //当前竞技sah场排名(不保存)
		2603: "ArenaHistoryRank", //竞技场历史排名
		2605: "ArenaBuyTimes", //竞技场今日购买次数
		2614: "RegionName", //登录地区
		2615: "Map_State", //地图状态 0,死亡，1复活
		2616: "Map_ReliveTime", //复活时间戳
		2617: "BossHomeEnergyVal", //boss之家（烽火连城）体力值
		2618: "BossHomeFightUserId", //boss之家（烽火连城）对手玩家id
		2620: "RankMatchScore", //排位赛积分
		2621: "RankMatchRank", //排位赛排名
		2651: "RankWorship", //本服排行榜膜拜
		2652: "RankWorshipUnion", //跨服排行榜膜拜
		2672: "MTBossDayBuyTimes", //多人boss今日购买次数
		2680: "OfficeLevel", //官职等级
		2681: "UserId", //角色Id
		2682: "TeamDunAccept", //组队副本时候默认接受
		2686: "FamilyTaskLevel", //世家事务等级
		2687: "Bubble", //气泡框
		2688: "FightValueMax", //历史最大战力值
		2690: "WorldLevel", //当前世界等级
		2691: "EscortNum", //九江粮道押镖次数
		3001: "RoleExp", //玩家经验
		3002: "ItemType_Coin2", //玉璧(充值货币)
		3003: "ItemType_Coin3", //元宝(绑元)
		3004: "ItemType_Coin4", //金币(游戏币)
		3011: "VipExp", //vip经验
		3012: "FamilyCoin", //世家币
		3015: "SkillExp", //技能经验
		3016: "ArenaMedal", //竞技勋章
		3017: "OfficeExp", //官职经验
		3018: "SkillCoin", //战技积分
		3019: "WJZhaoMuScore", //武将招募积分
		3020: "FamilyTaskExp", //世家事务exp
		3022: "DailyActVal", //日常活跃度
		3023: "WeekActVal", //周常活跃度
		3024: "HuarongTicket", //华容道券
		4301: "ExploreGemMaxStage", //三国探险-宝石秘矿-最高通过关卡
		4302: "ExploreGemCurrStage", //三国探险-宝石秘矿-当前挑战关卡
		11002: "Monster_Map_X", //地图所在的坐标x
		11003: "Monster_Map_Y", //地图所在的坐标Y
		11004: "Monster_FightCdEndTime", //怪物的战斗cd
		11005: "Monster_State", //怪物状态 0,死亡，1复活
		11006: "Monster_ReliveTime", //怪物复活时间戳
		11007: "Monster_OwnerId", //怪物归属玩家id
		13001: "FCurrHp", //战斗当前血量
		13002: "FMaxHp", //战斗最大血量
		13003: "FGeneralId", //战斗武将id
		13004: "FGeneralSkin", //战斗武将幻化id
		13005: "FMonsterId", //战斗怪物id
		13006: "FCampId", //战斗阵营id(魏蜀吴群)
		13007: "FBossShield", //世界boss盾值
		13008: "FBossParam", //世界boss攻击系数
		13009: "FBossDebuff", //世界bossdebuff
		13022: "FBeautyId", //红颜id
		14004: "SysSettingsInfo", //系统设置
	}

	/** 生命 */
	Hp = 0;
	/** 攻击 */
	Atk = 0;
	/** 防御 */
	Def = 0;
	/** 命中 */
	Hit = 0;
	/** 闪避 */
	Avd = 0;
	/** 暴击 */
	Cri = 0;
	/** 防暴击 */
	ACri = 0;
	/** 速度 */
	Speed = 0;
	/** 无视防御 */
	Atk1 = 0;
	/** 减免无视 */
	Def1 = 0;
	/** 伤害加深 */
	Atk2 = 0;
	/** 伤害减少 */
	Def2 = 0;
	/** 伤害增加% */
	Atk3 = 0;
	/** 伤害减少% */
	Def3 = 0;
	/** 暴击伤害增加 */
	Atk4 = 0;
	/** 暴击伤害减少 */
	Def4 = 0;
	/** 致命一击概率增加 */
	Atk5 = 0;
	/** 致命一击概率减少 */
	Def5 = 0;
	/** PVP伤害增加(万分比) */
	Atk6 = 0;
	/** VP伤害减少(万分比) */
	Def6 = 0;
	/** PVE伤害增加(万分比) */
	Atk7 = 0;
	/** PVE伤害减少(万分比) */
	Def7 = 0;
	/** 额外伤害 */
	ExtraHurt = 0;
	/** 仙击概率增加 */
	Atk8 = 0;
	/** 仙击概率减少 */
	Def8 = 0;
	/** 真实命中 */
	Hit_Real = 0;
	/** 真实暴击 */
	Cri_Real = 0;
	/** 神击概率增加 */
	AtkGod = 0;
	/** 神击概率减少 */
	DefGod = 0;
	/** 生命 */
	Hp_P = 0;
	/** 攻击 */
	Atk_P = 0;
	/** 防御 */
	Def_P = 0;
	/** 命中 */
	Hit_P = 0;
	/** 闪避 */
	Avd_P = 0;
	/** 暴击 */
	Cri_P = 0;
	/** 防暴击 */
	ACri_P = 0;
	/** 速度 */
	Speed_P = 0;
	/** 无视防御 */
	Atk1_P = 0;
	/** 减免无视 */
	Def1_P = 0;
	/** 伤害加深 */
	Atk2_P = 0;
	/** 伤害减少 */
	Def2_P = 0;
	/** 伤害增加% */
	Atk3_P = 0;
	/** 伤害减少% */
	Def3_P = 0;
	/** 暴击伤害增加 */
	Atk4_P = 0;
	/** 暴击伤害减少 */
	Def4_P = 0;
	/** 致命一击概率增加 */
	Atk5_P = 0;
	/** 致命一击概率减少 */
	Def5_P = 0;
	/** PVP伤害增加(万分比) */
	Atk6_P = 0;
	/** VP伤害减少(万分比) */
	Def6_P = 0;
	/** PVE伤害增加(万分比) */
	Atk7_P = 0;
	/** PVE伤害减少(万分比) */
	Def7_P = 0;
	/** 额外伤害 */
	ExtraHurt_P = 0;
	/** 仙击概率增加 */
	Atk8_P = 0;
	/** 仙击概率减少 */
	Def8_P = 0;
	/** 真实命中 */
	Hit_Real_P = 0;
	/** 真实暴击 */
	Cri_Real_P = 0;
	/** 神击概率增加 */
	AtkGod_P = 0;
	/** 神击概率减少 */
	DefGod_P = 0;
	/** 帐号ID */
	AccountId = 0;
	/** 用户所属于的渠道 */
	ChannelId = 0;
	/** 服务器名称 */
	AreaName = "";
	/** 创建区编号 */
	CreateAreaId = 0;
	/** 登录区编号 */
	LoginAreaId = 0;
	/** 显示区编号 */
	ShowAreaId = 0;
	/** 战区编号 */
	FightAreaId = 0;
	/** 用户离线时间 */
	LogoutTime = 0;
	/** 最后一次登录天：用于onDayChange 计算 */
	LastDay = 0;
	/** 最后一次登周：用于onWeekChange 计算 */
	LastWeek = 0;
	/** 最后一次登月：用于onMonthChange 计算 */
	LastMonth = 0;
	/** 今日在线时间 */
	DayOnlineTime = 0;
	/** 累计登录天数 */
	LoginDay = 0;
	/** 当月累计登录天数 */
	LoginDayInMonth = 0;
	/** 人物等级 */
	Level = 0;
	/** 昵称 */
	Nick = "";
	/** 性别 */
	Sex = 0;
	/** 用户头像 */
	HeadIcon = 0;
	/** 战力值 */
	FightValue = 0;
	/** 用户头像框 */
	HeadFrame = 0;
	/** 用户称号 */
	Title = 0;
	/** 玩家形象 */
	PlayerSkin = 0;
	/** 玩家的展示形象 */
	ShowId = 0;
	/** 是否在线 */
	IsOnline = 0;
	/** 是否自动战斗 */
	AutoFight = 0;
	/** 共充值多少rmb，分 */
	ChargeRmb = 0;
	/** 目前上阵的阵容编号 */
	LineUpId = 0;
	/** 地图所在的坐标x */
	Map_X = 0;
	/** 地图所在的坐标Y */
	Map_Y = 0;
	/** 开始移动时间 */
	Map_StartMoveTime = 0;
	/** 修改名字的次数 */
	ChangeNickTimes = 0;
	/** 下次修改名字的时间 */
	ChangeNickCd = 0;
	/** 军衔阶级 */
	ArmyLevel = 0;
	/** 月卡 */
	MonthCard = 0;
	/** 军衔星数 */
	ArmyStar = 0;
	/** 通关关卡 */
	Stage = 0;
	/** 实名认证防沉迷状态 */
	RealNameRealAuth = 0;
	/** vip等级 */
	VipLevel = 0;
	/** 总充值额度 */
	Recharge = 0;
	/** 今日充值额度 */
	RechargeToday = 0;
	/** 当月充值额度 */
	RechargeMonth = 0;
	/** 充值次数记录 */
	RechargeTimes = "";
	/** 是否打开过欢迎界面 */
	Welcome = 0;
	/** 坐骑幻化id */
	GradeHorse = 0;
	/** 羽翼幻化id */
	GradeWing = 0;
	/** 光武幻化id */
	GradeWeapon = 0;
	/** 萌宠幻化id */
	GradePet = 0;
	/** 幻化套装id */
	GradeSuitId = 0;
	/** 竞技场挑战次数 */
	ArenaTimes = 0;
	/** 竞技场挑战下次增加时间(秒) */
	ArenaNextTime = 0;
	/** 当前竞技sah场排名(不保存) */
	ArenaRank = 0;
	/** 竞技场历史排名 */
	ArenaHistoryRank = 0;
	/** 竞技场今日购买次数 */
	ArenaBuyTimes = 0;
	/** 登录地区 */
	RegionName = "";
	/** 地图状态 0,死亡，1复活 */
	Map_State = 0;
	/** 复活时间戳 */
	Map_ReliveTime = 0;
	/** boss之家（烽火连城）体力值 */
	BossHomeEnergyVal = 0;
	/** boss之家（烽火连城）对手玩家id */
	BossHomeFightUserId = 0;
	/** 排位赛积分 */
	RankMatchScore = 0;
	/** 排位赛排名 */
	RankMatchRank = 0;
	/** 本服排行榜膜拜 */
	RankWorship = 0;
	/** 跨服排行榜膜拜 */
	RankWorshipUnion = 0;
	/** 多人boss今日购买次数 */
	MTBossDayBuyTimes = 0;
	/** 官职等级 */
	OfficeLevel = 0;
	/** 角色Id */
	UserId = 0;
	/** 组队副本时候默认接受 */
	TeamDunAccept = 0;
	/** 世家事务等级 */
	FamilyTaskLevel = 0;
	/** 气泡框 */
	Bubble = 0;
	/** 历史最大战力值 */
	FightValueMax = 0;
	/** 当前世界等级 */
	WorldLevel = 0;
	/** 九江粮道押镖次数 */
	EscortNum = 0;
	/** 玩家经验 */
	RoleExp = 0;
	/** 玉璧(充值货币) */
	ItemType_Coin2 = 0;
	/** 元宝(绑元) */
	ItemType_Coin3 = 0;
	/** 金币(游戏币) */
	ItemType_Coin4 = 0;
	/** vip经验 */
	VipExp = 0;
	/** 世家币 */
	FamilyCoin = 0;
	/** 技能经验 */
	SkillExp = 0;
	/** 竞技勋章 */
	ArenaMedal = 0;
	/** 官职经验 */
	OfficeExp = 0;
	/** 战技积分 */
	SkillCoin = 0;
	/** 武将招募积分 */
	WJZhaoMuScore = 0;
	/** 世家事务exp */
	FamilyTaskExp = 0;
	/** 日常活跃度 */
	DailyActVal = 0;
	/** 周常活跃度 */
	WeekActVal = 0;
	/** 华容道券 */
	HuarongTicket = 0;
	/** 三国探险-宝石秘矿-最高通过关卡 */
	ExploreGemMaxStage = 0;
	/** 三国探险-宝石秘矿-当前挑战关卡 */
	ExploreGemCurrStage = 0;
	/** 地图所在的坐标x */
	Monster_Map_X = 0;
	/** 地图所在的坐标Y */
	Monster_Map_Y = 0;
	/** 怪物的战斗cd */
	Monster_FightCdEndTime = 0;
	/** 怪物状态 0,死亡，1复活 */
	Monster_State = 0;
	/** 怪物复活时间戳 */
	Monster_ReliveTime = 0;
	/** 怪物归属玩家id */
	Monster_OwnerId = 0;
	/** 战斗当前血量 */
	FCurrHp = 0;
	/** 战斗最大血量 */
	FMaxHp = 0;
	/** 战斗武将id */
	FGeneralId = 0;
	/** 战斗武将幻化id */
	FGeneralSkin = 0;
	/** 战斗怪物id */
	FMonsterId = 0;
	/** 战斗阵营id(魏蜀吴群) */
	FCampId = 0;
	/** 世界boss盾值 */
	FBossShield = 0;
	/** 世界boss攻击系数 */
	FBossParam = 0;
	/** 世界bossdebuff */
	FBossDebuff = 0;
	/** 红颜id */
	FBeautyId = 0;
	/** 系统设置 */
	SysSettingsInfo = "";
}
